package net.muxigame.outbreak.qa;
import com.google.gson.*;
import net.minecraft.client.*;
import net.minecraft.core.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.Difficulty;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.levelgen.WorldOptions;
import net.minecraft.world.level.levelgen.presets.WorldPresets;
import net.minecraft.server.level.ServerPlayer;
import net.muxigame.outbreak.*;
import net.muxigame.minigames.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
import java.nio.file.*;
import java.io.*;
import java.util.*;
/** QA-only actual post-conversion rendering, photometry and native bed packet validation. */
@Mod(value="outbreak_native_qa",dist=Dist.CLIENT)
public final class NativeClientQA {
 final Gson gson=new GsonBuilder().setPrettyPrinting().create();final JsonArray samples=new JsonArray(),points=new JsonArray(),bedEvents=new JsonArray();
 int ticks,stage,deadline,index,frames;boolean starting,done,pending;volatile JsonObject observed;volatile Throwable failure;
 public NativeClientQA(){NeoForge.EVENT_BUS.addListener(this::tick);NeoForge.EVENT_BUS.register(this);try(var input=Files.newInputStream(Path.of("map-input.json"))){var map=JsonParser.parseReader(new InputStreamReader(input,java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();for(var chapter:map.getAsJsonArray("chapters")){var ch=chapter.getAsJsonObject();var route=ch.getAsJsonArray("route");for(int i=0;i<route.size()&&!Files.exists(Path.of("detail-only.flag"));i++){var point=new JsonObject();point.addProperty("chapter",ch.get("id").getAsString());point.addProperty("routeIndex",i);point.add("position",route.get(i).deepCopy());point.add("next",route.get(Math.min(i+1,route.size()-1)).deepCopy());point.addProperty("capture",i==0||i==route.size()/2||i==route.size()-1);points.add(point);}}}catch(Exception e){throw new RuntimeException(e);}try(var in=Files.newInputStream(Path.of("map-details.json"))){var details=JsonParser.parseReader(new InputStreamReader(in,java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();for(var chapter:details.getAsJsonArray("chapters")){var ch=chapter.getAsJsonObject();var seen=new HashSet<String>();for(var prop:ch.getAsJsonArray("props")){var p=prop.getAsJsonObject();if(!p.get("status").getAsString().equals("placed"))continue;var kind=p.get("mapping").getAsString();if(!seen.add(kind))continue;var anchor=p.getAsJsonArray("nativeAnchor");var point=new JsonObject();point.addProperty("chapter",ch.get("chapter").getAsString());point.addProperty("routeIndex",points.size());point.addProperty("kind",kind);point.addProperty("propId",p.get("id").getAsString());point.add("anchor",anchor.deepCopy());var camera=anchor.deepCopy();camera.set(2,new JsonPrimitive(camera.get(2).getAsDouble()+3));point.add("position",camera);point.add("next",anchor.deepCopy());point.addProperty("capture",true);points.add(point);}}}catch(Exception e){throw new RuntimeException(e);}}
 @net.neoforged.bus.api.SubscribeEvent(priority=net.neoforged.bus.api.EventPriority.LOWEST,receiveCanceled=true)
 public void bedUse(net.neoforged.neoforge.event.entity.player.PlayerInteractEvent.RightClickBlock event){
  if(!(event.getEntity() instanceof ServerPlayer p)||!(p.level().getBlockState(event.getPos()).getBlock() instanceof net.minecraft.world.level.block.BedBlock))return;
  var row=new JsonObject();row.addProperty("hand",event.getHand().name());row.addProperty("canceled",event.isCanceled());row.addProperty("result",event.getCancellationResult().name());row.addProperty("pos",event.getPos().toShortString());bedEvents.add(row);
 }
 static OutbreakSession room(OutbreakGame game)throws Exception{var f=OutbreakGame.class.getDeclaredField("sessions");f.setAccessible(true);return ((List<OutbreakSession>)f.get(game)).stream().findFirst().orElse(null);}
 void write(String name,Object value)throws Exception{var target=Path.of(name);var temp=target.resolveSibling(name+".tmp");Files.writeString(temp,gson.toJson(value));Files.move(temp,target,StandardCopyOption.REPLACE_EXISTING);}
 void send(String action,String value){PacketDistributor.sendToServer(new GameNetwork.TerminalAction(UUID.randomUUID().toString(),"outbreak",action,value));}
 void observe(Minecraft mc){if(pending||mc.player==null||mc.getSingleplayerServer()==null)return;pending=true;var id=mc.player.getUUID();mc.getSingleplayerServer().execute(()->{try{var p=mc.getSingleplayerServer().getPlayerList().getPlayer(id);var game=OutbreakGame.active(p);var r=room(game);var d=game.snapshot(p);d.addProperty("phase",r==null?"NONE":r.phase.name());d.addProperty("dimension",p.level().dimension().location().toString());d.addProperty("diamonds",p.getInventory().countItem(Items.DIAMOND));d.addProperty("x",p.getX());d.addProperty("y",p.getY());d.addProperty("z",p.getZ());d.addProperty("blockLightFeet",p.level().getBrightness(LightLayer.BLOCK,p.blockPosition()));d.addProperty("blockLightEyes",p.level().getBrightness(LightLayer.BLOCK,BlockPos.containing(p.getEyePosition())));d.addProperty("skyLightEyes",p.level().getBrightness(LightLayer.SKY,BlockPos.containing(p.getEyePosition())));if(index<points.size()&&points.get(index).getAsJsonObject().has("anchor")){var a=points.get(index).getAsJsonObject().getAsJsonArray("anchor");var b=new BlockPos(a.get(0).getAsInt(),a.get(1).getAsInt(),a.get(2).getAsInt());d.addProperty("propState",p.level().getBlockState(b).toString());d.addProperty("bedStillPresent",p.level().getBlockState(b).getBlock() instanceof net.minecraft.world.level.block.BedBlock);}d.addProperty("entityTicking",p.serverLevel().isPositionEntityTicking(p.blockPosition()));observed=d;}catch(Throwable e){failure=e;}finally{pending=false;}});}
 void move(Minecraft mc){var point=points.get(index).getAsJsonObject().getAsJsonArray("position");var id=mc.player.getUUID();mc.getSingleplayerServer().execute(()->{try{var p=mc.getSingleplayerServer().getPlayerList().getPlayer(id);var r=room(OutbreakGame.active(p));r.directorEnabled=false;p.setInvulnerable(true);p.setNoGravity(true);
var sample=points.get(index).getAsJsonObject();if(sample.has("anchor")){
 var anchor=sample.getAsJsonArray("anchor");var target=new net.minecraft.world.phys.Vec3(anchor.get(0).getAsDouble()+.5,anchor.get(1).getAsDouble()+.65,anchor.get(2).getAsDouble()+.5);if(sample.get("kind").getAsString().equals("table"))target=target.add(0,.6,0);
 var level=p.server.getLevel(r.map.dimension());boolean found=false;
 for(int[] offset:new int[][]{{0,3},{0,-3},{3,0},{-3,0},{2,2},{-2,2},{2,-2},{-2,-2},{0,2},{0,-2}}){
  var feet=new net.minecraft.world.phys.Vec3(anchor.get(0).getAsDouble()+offset[0]+.5,anchor.get(1).getAsDouble(),anchor.get(2).getAsDouble()+offset[1]+.5);var foot=BlockPos.containing(feet);
  if(!level.getBlockState(foot).getCollisionShape(level,foot).isEmpty()||!level.getBlockState(foot.above()).getCollisionShape(level,foot.above()).isEmpty())continue;
  var eye=feet.add(0,1.62,0);boolean visible=true;for(double t=.05;t<.85;t+=.05){var at=BlockPos.containing(eye.lerp(target,t));if(!level.getBlockState(at).getCollisionShape(level,at).isEmpty()){visible=false;break;}}
  if(!visible)continue;point.set(0,new JsonPrimitive(feet.x-.5));point.set(1,new JsonPrimitive(feet.y));point.set(2,new JsonPrimitive(feet.z-.5));sample.addProperty("unobstructedDetailCamera",true);found=true;break;
 }
 if(!found)sample.addProperty("unobstructedDetailCamera",false);
}
p.teleportTo(p.server.getLevel(r.map.dimension()),point.get(0).getAsDouble()+.5,point.get(1).getAsDouble(),point.get(2).getAsDouble()+.5,0,0);p.fallDistance=0;}catch(Throwable e){failure=e;}});deadline=ticks+40;frames=0;}
 void tick(ClientTickEvent.Post event){if(done)return;var mc=Minecraft.getInstance();ticks++;try{
  if(failure!=null)throw new RuntimeException(failure);if(ticks>12000)throw new IllegalStateException("Audit deadline reached");
  if(!starting){if(ticks<30||mc.getOverlay()!=null||mc.screen==null)return;starting=true;mc.createWorldOpenFlows().createFreshLevel("outbreak-map-baseline",new LevelSettings("Outbreak map baseline QA",GameType.SURVIVAL,false,Difficulty.PEACEFUL,true,new GameRules(),WorldDataConfiguration.DEFAULT),new WorldOptions(817131L,false,false),r->r.registryOrThrow(Registries.WORLD_PRESET).getHolderOrThrow(WorldPresets.FLAT).value().createWorldDimensions(),mc.screen);return;}
  if(mc.player==null||mc.getSingleplayerServer()==null)return;if(mc.screen!=null&&stage>0)mc.setScreen(null);if(ticks%10==0)observe(mc);if(ticks%100==0)write("audit-progress.json",Map.of("stage",stage,"index",index,"ticks",ticks,"observation",observed==null?new JsonObject():observed));if(ticks<deadline||observed==null&&stage>0)return;
  if(stage==0){var id=mc.player.getUUID();mc.getSingleplayerServer().execute(()->{var p=mc.getSingleplayerServer().getPlayerList().getPlayer(id);p.setInvulnerable(true);p.getInventory().add(new ItemStack(Items.DIAMOND,3));});send("createConfigured","{\"map\":\"lostschool\",\"mode\":\"CAMPAIGN\",\"difficulty\":1}");stage=1;deadline=ticks+50;return;}
  if(stage==1){var rooms=observed.getAsJsonArray("rooms");if(rooms.isEmpty()||!rooms.get(0).getAsJsonObject().get("mapReady").getAsBoolean())return;send("start","");stage=2;deadline=ticks+240;return;}
  if(stage==2){if(!observed.get("phase").getAsString().equals("START_ROOM"))return;move(mc);stage=3;return;}
  if(stage==3){var point=points.get(index).getAsJsonObject();var pos=point.getAsJsonArray("position");if(!mc.player.level().dimension().location().toString().equals("muxi_outbreak:campaign")||mc.player.distanceToSqr(pos.get(0).getAsDouble()+.5,pos.get(1).getAsDouble(),pos.get(2).getAsDouble()+.5)>4||!observed.get("entityTicking").getAsBoolean())return;var next=point.getAsJsonArray("next");double dx=next.get(0).getAsDouble()-pos.get(0).getAsDouble(),dz=next.get(2).getAsDouble()-pos.get(2).getAsDouble();mc.player.setYRot((float)Math.toDegrees(Math.atan2(-dx,dz)));float pitch=0;if(point.has("anchor")){var a=point.getAsJsonArray("anchor");double y=a.get(1).getAsDouble()+.65+(point.get("kind").getAsString().equals("table")?.6:0);pitch=(float)Math.toDegrees(Math.atan2(mc.player.getEyeY()-y,Math.hypot(dx,dz)));}mc.player.setXRot(pitch);mc.player.yRotO=mc.player.getYRot();mc.player.xRotO=pitch;if(point.has("kind")&&point.get("kind").getAsString().equals("bed")){if(frames==14){var a=point.getAsJsonArray("anchor");var b=new BlockPos(a.get(0).getAsInt(),a.get(1).getAsInt(),a.get(2).getAsInt());var hit=new net.minecraft.world.phys.BlockHitResult(net.minecraft.world.phys.Vec3.atCenterOf(b),Direction.UP,b,false);mc.gameMode.useItemOn(mc.player,net.minecraft.world.InteractionHand.MAIN_HAND,hit);mc.gameMode.useItemOn(mc.player,net.minecraft.world.InteractionHand.OFF_HAND,hit);}if(++frames<60)return;if(!observed.get("bedStillPresent").getAsBoolean())throw new IllegalStateException("Native bed use destroyed campaign scenery");}else if(++frames<15)return;var row=observed.deepCopy();row.add("sample",point.deepCopy());row.addProperty("gamma",mc.options.gamma().get());row.addProperty("clientDimension",mc.player.level().dimension().location().toString());if(point.get("capture").getAsBoolean()){String filename="after-"+point.get("chapter").getAsString()+"-"+point.get("routeIndex").getAsInt()+".png";try(var image=Screenshot.takeScreenshot(mc.getMainRenderTarget())){image.writeToFile(Path.of(filename));}row.addProperty("screenshot",filename);}samples.add(row);write("baseline-route-light.json",samples);index++;if(index<points.size()){move(mc);return;}send("leave","");stage=4;deadline=ticks+60;frames=0;return;}
  if(stage==4){if(!observed.get("phase").getAsString().equals("NONE")||!observed.get("dimension").getAsString().equals("minecraft:overworld")||observed.get("diamonds").getAsInt()!=3||!mc.player.level().dimension().location().toString().equals("minecraft:overworld")||mc.player.getInventory().countItem(Items.DIAMOND)!=3)return;if(++frames<30)return;if(Files.exists(Path.of("detail-only.flag"))&&(bedEvents.size()!=6||bedEvents.asList().stream().anyMatch(e->!e.getAsJsonObject().get("canceled").getAsBoolean())))throw new IllegalStateException("Bed right-click events were not received/canceled for all three chapters and both hands");write("bed-events.json",bedEvents);write("audit-result.json",Map.of("passed",true,"baselineOnly",false,"sampledRoutePositions",samples.size(),"realLocalNetworkPlayer",true,"hiddenWindow",true,"mcefLoaded",false,"routeMovementAssisted",true,"directorPausedForSurvey",true,"normalClientAndServerRestoreVerified",true,"mappingImplementationWritten",true));done=true;mc.stop();}
 }catch(Throwable e){done=true;e.printStackTrace();try{write("bed-events.json",bedEvents);write("audit-result.json",Map.of("passed",false,"error",e.toString()));}catch(Exception ignored){}mc.stop();}}
}
