"""Boot an isolated, loopback-only QA server. Never launches the production start script."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import secrets
import shutil
import socket
import subprocess
import sys
import threading

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
import build


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--heap',type=int,default=1024)
    parser.add_argument('--full',action='store_true',help='load the current complete Better MC server mod set in the isolated fixture')
    parser.add_argument('--view-distance',type=int,default=2)
    parser.add_argument('--engine-tests',action='store_true',help='include the isolated server-engine test addon; never deploy this addon')
    args=parser.parse_args()
    home=ROOT/'build/qa-server'
    home.mkdir(parents=True,exist_ok=True)
    try:
        connection=socket.create_connection(('127.0.0.1',25683),timeout=1)
    except OSError:
        pass
    else:
        connection.close()
        raise SystemExit('QA port already occupied: stop only the previous QA instance first')
    source=ROOT.parent/'bmc5server'
    libraries=home/'libraries'
    if not libraries.exists():
        subprocess.run(['cmd','/c','mklink','/J',str(libraries),str(source/'libraries')],check=True,capture_output=True)
    (home/'mods').mkdir(exist_ok=True)
    # This directory is exclusively generated by this harness, never the live mod directory.
    for old in (home/'mods').glob('*.jar'):old.unlink()
    pack=[]
    if args.full:
        for file in sorted((source/'mods').glob('*.jar')):
            if file.name.startswith('muxi-outbreak-'):continue
            target=home/'mods'/file.name
            shutil.copy2(file,target)
            pack.append({'file':file.name,'sha256':hashlib.sha256(target.read_bytes()).hexdigest()})
        for name in ('config','defaultconfigs','kubejs','tacz','tlm_custom_pack'):
            if (source/name).is_dir():
                shutil.copytree(source/name,home/name,dirs_exist_ok=True,
                    ignore=shutil.ignore_patterns('*.bak','*.log','session.lock'))
        (home/'config/muxi-game-core.json').write_text(json.dumps({'schema':1,'features':{
            'identity':{'enabled':False},'login':{'enabled':False}}}),encoding='utf-8')
        web=home/'config/webdisplays_common.toml'
        if web.exists():
            import re
            web.write_text(re.sub(r'miniserv_port\s*=\s*\d+','miniserv_port = 0',web.read_text(encoding='utf-8-sig')),encoding='utf-8')
        for relative in ('config/resourceful-config-web.json','kubejs/config/web_server.json'):
            target=home/relative
            if target.exists():
                data=json.loads(target.read_text(encoding='utf-8-sig'))
                data['enabled']=False
                data.pop('auth',None)
                data.pop('validator',None)
                target.write_text(json.dumps(data),encoding='utf-8')
        (home/'full-pack-manifest.json').write_text(json.dumps(pack,ensure_ascii=False,indent=2),encoding='utf-8')
    from qa_dependencies import install
    integration_files=install(home)
    jar=ROOT/'build/libs'/json.loads((ROOT/'build/release.json').read_text(encoding='utf-8'))['artifact']
    shutil.copy2(jar,home/'mods'/jar.name)
    if args.engine_tests:
        from build_engine_harness import build_harness
        build_harness(home)
    # Test instance, no real player data, no real login credentials, no public socket.
    password=secrets.token_urlsafe(24)
    properties={
        'server-ip':'127.0.0.1','server-port':'25683','enable-rcon':'true','rcon.port':'25684',
        'rcon.password':password,'broadcast-rcon-to-ops':'false','online-mode':'false',
        'enforce-secure-profile':'false','spawn-protection':'0','allow-flight':'true',
        'view-distance':str(max(2,min(8,args.view_distance))),'simulation-distance':'2','max-players':'4','sync-chunk-writes':'false',
        'max-tick-time':'120000','gamemode':'survival','difficulty':'normal',
        'level-type':'minecraft:flat','generate-structures':'false','spawn-npcs':'false',
        'spawn-animals':'false','spawn-monsters':'false','level-name':'qa-world',
        'generator-settings':json.dumps({'layers':[{'block':'minecraft:bedrock','height':1},{'block':'minecraft:stone','height':3}], 'biome':'minecraft:plains'}),
    }
    (home/'server.properties').write_text('\n'.join(f'{k}={v}' for k,v in properties.items())+'\n',encoding='utf-8')
    shutil.copy2(source/'eula.txt',home/'eula.txt')
    _,java=build.java_tools(None)
    command=[str(java),'-Xms256M',f'-Xmx{args.heap}M','-XX:ActiveProcessorCount=2',
             '-Dfile.encoding=UTF-8','-Dstdout.encoding=UTF-8','-Dstderr.encoding=UTF-8',
             '-Djava.awt.headless=true','@libraries/net/neoforged/neoforge/21.1.250/win_args.txt','nogui']
    if args.engine_tests:command.insert(1,'-Dmuxi.outbreak.qa=true')
    log=home/'console.log'
    with log.open('w',encoding='utf-8',buffering=1) as out:
        process=subprocess.Popen(command,cwd=home,stdin=subprocess.PIPE,stdout=out,stderr=subprocess.STDOUT,
                                 text=True,encoding='utf-8',creationflags=getattr(subprocess,'BELOW_NORMAL_PRIORITY_CLASS',0))
        (home/'run.json').write_text(json.dumps({'pid':process.pid,'host':'127.0.0.1','port':25683,'rconPort':25684,
            'rconPassword':password,'jarSha256':hashlib.sha256(jar.read_bytes()).hexdigest(),'heapMB':args.heap,
            'fullPack':args.full,'copiedServerMods':len(pack),'integrationDependencies':integration_files},indent=2),encoding='utf-8')
        print(f'QA_PROCESS pid={process.pid} port=25683 heapMB={args.heap} log={log}',flush=True)
        # Parent retains stdin; E2E harness uses RCON. A stop file is a fallback for failed boot/RCON.
        stop=home/'stop.request'
        if stop.exists():stop.unlink()
        while process.poll() is None:
            if stop.exists():
                stop.unlink();process.stdin.write('stop\n');process.stdin.flush()
            threading.Event().wait(.5)
        print('QA_PROCESS_EXIT',process.returncode,flush=True)
        raise SystemExit(process.returncode)


if __name__=='__main__':main()
